### ISSUE TITLE
Payload always as JSON - FormData can't be sent

### ISSUE THREAD

**Issue by sgruetter** [max-favilli/helper-xhr#1]
[Line 69](https://github.com/max-favilli/helper-xhr/blob/8818c067901a4523eb41300498c9e1d8a88a8d27/src/helper-xhr.js#L69) always serializes the payload as JSON. This prevents sending [FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData) for convenient file uploads from the JavaScript context.

A simple change to address this issue would be to change the linked line to 
```
this.xhr.send(payload instanceof FormData ? payload : JSON.stringify(payload));
```

For this to work, the `Content-Type` needs to be set to `false` (or probably just not set at all) - the browser will then automatically add the correct header, generating the boundary safely:

```
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryCVhVLnU1LMSmW9HB
```

...and file upload works. But I think that's for the consumer of the lib to handle.

@max-favilli  If you want, I can provide a PR. It would be nice to have this capability in helper-xhr as it's very handy, and as lightweight as it gets :-)

**Comment by max-favilli** [comment]
I have totally missed your message. But just updated the repository adding that same check.
